apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - app/mcl.yaml
  - app/mysql.yaml
  - app/bot.yaml
namespace: qqbot
configMapGenerator:
  - files:
      - config/AutoLogin.yml
      - config/device.json
      - config/setting.yml
    name: mcl-config
  - files:
      - config/docker.cnf
    name: mysql-config
generatorOptions:
  disableNameSuffixHash: true
