apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-data
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner
parameters:
  archiveOnDelete: "true"
reclaimPolicy: Retain
volumeBindingMode: Immediate
