name: 问题：使用遇到问题
description: 此模板适用于解决使用 Madoka 的过程中遇到的问题。
title: "【问题】："
labels: help
body:
  - type: markdown
    attributes:
      value: | 
        请务必认真填写，足够的信息能帮助我们快速定位问题并及时修复。
  - type: checkboxes
    id: checks
    attributes:
      label: 检查清单
      description: 请认真检查以下清单中的每一项，并在相符的项前打勾。
      options:
        - label: 已经搜索过，没有发现类似 issue。
        - label: 已经搜索过[文档](https://madoka.colsrch,cn/)，没有发现相关内容。
        - label: 已经尝试使用过[最新版](https://github.com/MadokaProject/Madoka/releases)，问题依旧存在。
  - type: input
    id: madoka-version
    attributes:
      label: Madoka 版本
      description: 请输入 Madoka 版本号（可在 app/core/config.py 中找到）或 Madoka 的 Commit ID（Madoka 目录下执行 `git log -1` 查看）。
      placeholder: "如: 3.2.2 或 b95bf81"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: 问题描述
      description: 请告诉我们发生了什么？
      placeholder:  请详细描述您所遇到的情况：复现步骤、操作过程、Madoka 安装方式、截图等内容。
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: 环境信息
      description: 请提供您的环境信息，打开终端在 Madoka 目录下执行命令获取内容。
      value: |
        <details><summary>python</summary><p>

        ```
        在这里粘贴替换 `python --version` 输出的信息
        ```

        </p></details>

        <details><summary>requirements</summary><p>

        ```
        在这里粘贴替换 `pip list` 输出的信息
        ```

        </p></details>
        