name: Publish to Docker Hub

on:
  release:
    types:
      - created

jobs:
  docker-publish:
    name: docker-publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Init resources
        run: git clone -b ${{ github.ref_name }} https://github.com/MadokaProject/Madoka.git ./k8s/images/Madoka
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t colsrch/madoka:${{ github.ref_name }} ./k8s/images
      - name: Push
        run: docker push colsrch/madoka:${{ github.ref_name }}