name: Publish to Docker Hub

on:
  push:
    branches:
      - release
      - master

jobs:
  release:
    if: github.ref == 'refs/heads/release'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Init resources
        run: git clone -b release https://github.com/MadokaProject/Madoka.git ./k8s/images/Madoka
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t colsrch/madoka:latest ./k8s/images
      - name: Push
        run: docker push colsrch/madoka:latest
  master:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Init resources
        run: git clone -b master https://github.com/MadokaProject/Madoka.git ./k8s/images/Madoka
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t colsrch/madoka:stable ./k8s/images
      - name: Push
        run: docker push colsrch/madoka:stable