name: Sync Coding

on:
  push:
    branches:
      - release
      - master
  release:
    types: [published]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Run Curl
        run: |
          curl -u ${{ secrets.CODING_TOKEN_API }} \
             -v -X POST  'https://madokaproject.coding.net/api/cci/job/1548242/trigger' \
             -H 'Content-Type: application/json' \
             -d '
              {
                "envs": [
                  {
                    "name": "BRANCH",
                    "value": "${{ github.ref_name }}",
                    "sensitive": 0
                  }
                ]
              }'
